Functionality
Theodoraldo/react-capstone-metrics pull request #2
Opened 2023-06-27 21:54 UTC by Theodoraldo

At this juncture, I :

- [ ] Handle events in a React app.
- [ ] Use styles in a React app.
- [ ] Use store, actions and reducers in React.
- [ ] Write integration tests with a React testing library.
- [ ] Connect React and Redux.
- [ ] Use React Router.
- [ ] Use React props.
- [ ] Use React components.

2023-06-28 13:51 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Theodoraldo,

Good job so far!
✔️ Implementation of unique routing
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 13:51 UTC, TedLivist commented on README.md
> +- [Live Demo](soon)
- [ ] Kindly ensure you deploy your app and provide its link in the README.

  ![image](https://github.com/Theodoraldo/react-capstone-metrics/assets/36542986/4ebf72f3-2ebd-44c4-b817-cf1fbe408f6e)

- [ ] Kindly record a video presentation of your app and include the link in the README. Ensure you outline the piece of code you are proud of or find interesting.

2023-06-28 13:51 UTC, TedLivist commented on README.md
> +```
- [ ] One of your tests is failing. Kindly fix that.

  ![image](https://github.com/Theodoraldo/react-capstone-metrics/assets/36542986/6c50d34c-85fd-46c9-ac70-7373ad468f4b)

2023-06-28 13:51 UTC, TedLivist commented on src/components/Home.js
> +export default function Home() {
- [ ] Your Homepage should have a search or filtering feature that allows users to filter items on the homepage. Kindly implement that.

2023-06-30 04:13 UTC, CollinsTatang requested changes
Hi @Theodoraldo , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your app was deployed successfully. ✔️ 
- All your app test pass successfully. ✔️ 

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-30 04:13 UTC, CollinsTatang commented on src/components/Home.js
> +    </>
- [ ] Your search box is still not working as mentioned by the previous reviewer on the homepage.
 - Please user should be able to filter or search for a particular continent using the search box on the homepage.

2023-06-30 08:11 UTC, osamaashraf6 approved these changes
Hi @Theodoraldo 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (3)](https://github.com/tumainimaganiko/global-atlas/assets/83360636/d88cea07-6b03-4c9c-bbb8-7c3997d6e0eb)

## Highlights🎉🎉

- [ ] Use the redux for the state management💯
- [ ] All tests passed 👍
- [ ] Has a live demo for the project🚀

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 08:16 UTC, merged